version: '3'
services:
  server:
    build:
      context: ./enerclic_server
      dockerfile: Dockerfile
    ports:
      - 9999:9999
    volumes:
      - ./enerclic_server/logs:/app/logs
  client:
    build:
      context: ./enerclic_client
      dockerfile: Dockerfile
